<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-OET6KL6" failures="4" tests="15" name="Tests.VisitorLoginTest" time="112.159" errors="0" timestamp="2024-05-22T15:49:05 IST" skipped="0">
  <testcase classname="Tests.VisitorLoginTest" name="TC_001_VerifyVisitorLoginModuleDisplayed" time="2.083"/>
  <system-out/>
  <testcase classname="Tests.VisitorLoginTest" name="TC_002_VerifySubmitButtonWithoutEnteringFields" time="18.682"/>
  <system-out/>
  <testcase classname="Tests.VisitorLoginTest" name="TC_003_VerifyVisitorEmpIDTextboxCharacterLimit" time="4.640">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at Modules.VisitorLogin_Module.validateMaxTextLimitInEmpIDTextbox(VisitorLogin_Module.java:216)
at Tests.VisitorLoginTest.TC_003_VerifyVisitorEmpIDTextboxCharacterLimit(VisitorLoginTest.java:49)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at Tests.Main.main(Main.java:33)
]]>
    </failure>
  </testcase> <!-- TC_003_VerifyVisitorEmpIDTextboxCharacterLimit -->
  <system-out/>
  <testcase classname="Tests.VisitorLoginTest" name="TC_004_VerifyVisitorEmpIDTextboxAcceptsSpecialCharacters" time="2.208"/>
  <system-out/>
  <testcase classname="Tests.VisitorLoginTest" name="TC_005_VerifyVisitorEmpIDTextboxAcceptsNumbers" time="2.163"/>
  <system-out/>
  <testcase classname="Tests.VisitorLoginTest" name="TC_006_VerifyVisitorNameTextboxCharacterLimit" time="3.859">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at Modules.VisitorLogin_Module.validateMaxTextLimitInNameTextbox(VisitorLogin_Module.java:253)
at Tests.VisitorLoginTest.TC_006_VerifyVisitorNameTextboxCharacterLimit(VisitorLoginTest.java:67)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at Tests.Main.main(Main.java:33)
]]>
    </failure>
  </testcase> <!-- TC_006_VerifyVisitorNameTextboxCharacterLimit -->
  <system-out/>
  <testcase classname="Tests.VisitorLoginTest" name="TC_007_VerifyVisitorNameTextboxAcceptsSpecialCharacters" time="2.251"/>
  <system-out/>
  <testcase classname="Tests.VisitorLoginTest" name="TC_008_VerifyVisitorNameTextboxAcceptsNumbers" time="2.038"/>
  <system-out/>
  <testcase classname="Tests.VisitorLoginTest" name="TC_009_VerifyDesignationTextboxCharacterLimit" time="4.111">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at Modules.VisitorLogin_Module.validateMaxTextLimitInDesignationTextbox(VisitorLogin_Module.java:289)
at Tests.VisitorLoginTest.TC_009_VerifyDesignationTextboxCharacterLimit(VisitorLoginTest.java:85)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at Tests.Main.main(Main.java:33)
]]>
    </failure>
  </testcase> <!-- TC_009_VerifyDesignationTextboxCharacterLimit -->
  <system-out/>
  <testcase classname="Tests.VisitorLoginTest" name="TC_010_VerifyDesignationTextboxAcceptsSpecialCharacters" time="2.283"/>
  <system-out/>
  <testcase classname="Tests.VisitorLoginTest" name="TC_011_VerifyDesignationTextboxAcceptsNumbers" time="2.108"/>
  <system-out/>
  <testcase classname="Tests.VisitorLoginTest" name="TC_012_VerifyRemarksTextboxCharacterLimit" time="4.061">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at Modules.VisitorLogin_Module.validateMaxTextLimitInRemarksTextbox(VisitorLogin_Module.java:327)
at Tests.VisitorLoginTest.TC_012_VerifyRemarksTextboxCharacterLimit(VisitorLoginTest.java:103)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at Tests.Main.main(Main.java:33)
]]>
    </failure>
  </testcase> <!-- TC_012_VerifyRemarksTextboxCharacterLimit -->
  <system-out/>
  <testcase classname="Tests.VisitorLoginTest" name="TC_013_VerifyRemarksTextboxAcceptsSpecialCharacters" time="2.575"/>
  <system-out/>
  <testcase classname="Tests.VisitorLoginTest" name="TC_014_Verify_RemarksTextboxAcceptsNumbers" time="7.340"/>
  <system-out/>
  <testcase classname="Tests.VisitorLoginTest" name="TC_015_Verify_Visitor_Upload" time="51.757"/>
  <system-out/>
</testsuite> <!-- Tests.VisitorLoginTest -->
